"""
Run this script to compile the cffi API-mode extension:
"""

import importlib
import shutil
import sys
from pathlib import Path
import tempfile

import cffi

_ROOT = Path(__file__).parent.parent
_QLCP_INCLUDE = _ROOT / "qlcp" / "include"
_LIB_DIR = _ROOT / "libqretprop" / "_lib"
_PROTOCOL_DIR = _ROOT / "libqretprop" / "_protocol"

ffi = cffi.FFI()
ffi.cdef((_QLCP_INCLUDE / "qlcp_lib_cffi.h").read_text())
ffi.set_source(
    "_qlcp",  # flat name — no dots
    '#include "qlcp_lib.h"',
    include_dirs=[str(_QLCP_INCLUDE)],
    libraries=["qlcp"],
    library_dirs=[str(_LIB_DIR)],
    extra_link_args=[f"-Wl,-rpath,{_LIB_DIR}"],
)


def _generate_stub(lib) -> None:
    enums = {name: getattr(lib, name) for name in dir(lib) if isinstance(getattr(lib, name), int)}
    functions = [name for name in dir(lib) if callable(getattr(lib, name))]

    lines = [
        "# Auto-generated by _build.py — do not edit",
        "from cffi.api import FFI",
        "from typing import Any",
        "",
        "ffi: FFI",
        "",
        "class _Lib:",
        *(f"    {name}: int  # {value:#04x}" for name, value in sorted(enums.items())),
        *(f"    def {name}(self, *args: Any) -> Any: ..." for name in sorted(functions)),
        "",
        "lib: _Lib",
        "",
    ]

    (_PROTOCOL_DIR / "_qlcp.pyi").write_text("\n".join(lines))


if __name__ == "__main__":
    _PROTOCOL_DIR.mkdir(parents=True, exist_ok=True)
    (_PROTOCOL_DIR / "__init__.py").write_text("# Auto-generated by _build.py — do not edit\n")

    with tempfile.TemporaryDirectory() as tmp:
        output = ffi.compile(tmpdir=tmp, verbose=True)
        shutil.copy(output, _PROTOCOL_DIR / Path(output).name)

    sys.path.insert(0, str(_ROOT))
    lib = importlib.import_module("libqretprop._protocol._qlcp").lib
    _generate_stub(lib)