services:
  server:
    # Build the image from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - redis
      - logs
    network_mode: "host"  # Use host networking for SSDP
    environment:
      - PROP_CONFIG=/app/config.yaml # Default config file location

    # Allow manual interaction with the container (cli)
    stdin_open: true
    tty: true

    volumes:
      - ./config.yaml:/app/config.yaml  # Mount local config file for development

    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync+restart
          path: ./libqretprop
          target: /app/libqretprop
          # Exclude the project virtual environment
          ignore:
            - .venv/
        # Rebuild the image if dependencies change by checking uv.lock
        - action: sync+restart
          path: ./config.yaml
          target: /app/config.yaml

        - action: rebuild
          path: ./uv.lock
  logs:
    build:
      context: .
      dockerfile: Dockerfile.logs
    depends_on:
      - redis
      
    # Required for consistency of shared config of redis ip
    # Normal containers cannot access localhost, host networked containers cannot use docker internal DNS
    network_mode: "host"
    environment:
      - PROP_CONFIG=/app/config.yaml # Default config file location
    tty: true

    volumes:
      - ./config.yaml:/app/config.yaml  # Mount local config file for development

    develop:
      watch:
        # Sync script changes for development
        - action: sync+restart
          path: ./qretproptools/cli/see_logs
          target: /app/qretproptools/cli/see_logs

  media:
    image: "bluenviron/mediamtx:latest"
    network_mode: "host"
    depends_on:
      - server
    environment:
    # Use a different RTSP port to avoid conflicts with local testing
    # This port isn't being accessed externally, changing it is fine
      - MTX_RTSPADDRESS=:8558
      - MTX_RTMPADDRESS=:7935
      - MTX_API=yes
      # Windows firewall blocks UDP, so use TCP for development streams
      - MTX_WEBRTCLOCALTCPADDRESS=:8189

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
          - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

    develop:
      watch:
        # Restart on redis.conf changes
        # Sync doesn't actually work here because of the volume mount
        - action: restart
          path: ./redis.conf
          target: /usr/local/etc/redis/redis.conf
