services:
  server:
    # Build the image from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host" # Use host networking for SSDP
    environment:
      - PROP_CONFIG=/app/config.yaml # Default config file location

    # Allow manual interaction with the container (cli)
    stdin_open: true
    tty: true

    volumes:
      - ./config.yaml:/app/config.yaml # Mount local config file for development
      - ./recordings:/app/recordings # Mount local directory for audio recordings

    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync+restart
          path: ./libqretprop
          target: /app/libqretprop
          # Exclude the project virtual environment
          ignore:
            - .venv/
            - _lib/
            - _protocol/
        # Rebuild the image if dependencies change by checking uv.lock
        - action: sync+restart
          path: ./config.yaml
          target: /app/config.yaml

        - action: rebuild
          path: ./uv.lock
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./hatch_build.py
        - action: rebuild
          path: ./qlcp

  media:
    image: "bluenviron/mediamtx:latest"
    network_mode: "host"
    depends_on:
      - server
    environment:
      # Use a different RTSP port to avoid conflicts with local testing
      # This port isn't being accessed externally, changing it is fine
      - MTX_RTSPADDRESS=:8558
      - MTX_RTMPADDRESS=:7935
      - MTX_API=yes
      # Windows firewall blocks UDP, so use TCP for development streams
      - MTX_WEBRTCLOCALTCPADDRESS=:8189
    volumes:
      - ./recordings/mediamtx:/recordings

  mumble:
    image: mumblevoip/mumble-server:latest
    ports:
      - "64738:64738"
      - "64738:64738/udp"
    volumes:
      - ./murmur.ini:/etc/mumble/murmur.ini
      - murmur-data:/data

  mumble-web:
    image: rankenstein/mumble-web:latest
    ports:
      - "8080:8080"
    environment:
      - MUMBLE_SERVER=mumble:64738
    depends_on:
      - mumble

volumes:
  murmur-data:
