accounts:
  camera:
    username: propcam
    password: propteambestteam

services:
  mediamtx:
    ip: localhost
    api_port: 9997
  mumble:
    ip: localhost
    port: 64738
    password: ""
    temp_recording_dir: /tmp/mumble_recordings
    recording_dir: ./recordings/mumble

cameras:
  - ip: 192.168.1.5
    onvif_port: 2020
  - ip: 192.168.1.6
    onvif_port: 2020
  - ip: 192.168.1.7
    onvif_port: 2020
