FROM python:3.13-alpine3.22@sha256:ab45bd32143151fe060d48218b91df43a289166e72ec7877823b1c972580bed3

# Install uv
COPY --from=ghcr.io/astral-sh/uv@sha256:9a23023be68b2ed09750ae636228e903a54a05ea56ed03a934d00fe9fbeded4b /uv /uvx /bin/
WORKDIR /app

# Install dependencies
# Use host dependencies by default during development to improve build times
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --no-dev

# Copy the project into the image
ADD pyproject.toml uv.lock /app/
ADD qretproptools/cli/see_logs /app/qretproptools/cli/see_logs

# Dependencies require the packages to exist
RUN mkdir /app/libqretprop
RUN touch /app/libqretprop/__init__.py /app/qretproptools/__init__.py

# Add config-specific files
ADD libqretprop/configManager.py /app/libqretprop/configManager.py
ADD config.yaml /app/config.yaml

# Sync the project
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-dev

CMD ["uv", "run", "--no-dev", "see_logs", "-e", "-d", "-s"]
