FROM python:3.13-alpine3.22@sha256:ab45bd32143151fe060d48218b91df43a289166e72ec7877823b1c972580bed3 AS qlcp-builder

RUN apk add --no-cache gcc musl-dev cmake make

COPY qlcp/ /build/qlcp/
WORKDIR /build/qlcp/build

RUN cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release && \
    cmake --build . --target qlcp && \
    gcc -E -P ../include/qlcp_lib.h -o qlcp_lib_expanded.h

# Final stage
FROM python:3.13-alpine3.22@sha256:ab45bd32143151fe060d48218b91df43a289166e72ec7877823b1c972580bed3

COPY --from=ghcr.io/astral-sh/uv@sha256:9a23023be68b2ed09750ae636228e903a54a05ea56ed03a934d00fe9fbeded4b /uv /uvx /bin/
WORKDIR /app

# Install QLCP from builder stage
COPY --from=qlcp-builder /build/qlcp/build/libqlcp.so /app/lib/libqlcp.so
COPY --from=qlcp-builder /build/qlcp/build/qlcp_lib_expanded.h /app/lib/qlcp_lib_expanded.h

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --no-install-project --no-dev

ADD . /app

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --no-dev

CMD ["uv", "run", "--no-dev", "start_server"]