"""Hatchling hook for the qlcp protocol build.

`uv sync` and `uv build` load this hook, which builds libqlcp with CMake,
expands the public header for CFFI, then compiles the `_qlcp` extension.
"""

from __future__ import annotations
import importlib
import os
import shutil
import subprocess
import sys
import sysconfig
import tempfile
from pathlib import Path
from typing import Any

import cffi
from hatchling.builders.hooks.plugin.interface import BuildHookInterface


ROOT = Path(__file__).resolve().parent
QLCP_DIR = ROOT / "qlcp"
QLCP_INCLUDE = QLCP_DIR / "include"
LIB_DIR = ROOT / "libqretprop" / "_lib"
PROTOCOL_DIR = ROOT / "libqretprop" / "_protocol"
LIBQLCP = LIB_DIR / "libqlcp.so"
EXPANDED_HEADER = LIB_DIR / "qlcp_lib_expanded.h"
SKIP_ENV = "SKIP_PROTOCOL_BUILD"
GENERATED_BANNER = "# Auto-generated by hatch_build.py - do not edit"
BUILD_TARGETS = {"wheel", "editable"}

def run(args: list[str], *, capture: bool = False) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(  # noqa: S603
            args,
            check=True,
            stdout=subprocess.PIPE if capture else None,
            text=capture,
        )
    except FileNotFoundError as exc:
        message = (
            f"Required build command not found: {args[0]!r}. Install a C toolchain, "
            "CMake, and make/ninja for local qlcp builds."
        )
        raise RuntimeError(message) from exc

def clean_protocol_artifacts() -> None:
    LIB_DIR.mkdir(parents=True, exist_ok=True)
    PROTOCOL_DIR.mkdir(parents=True, exist_ok=True)

    for path in (LIBQLCP, EXPANDED_HEADER, PROTOCOL_DIR / "_qlcp.pyi"):
        if path.exists():
            path.unlink()

    for pattern in ("_qlcp*.so", "_qlcp*.c", "_qlcp*.o"):
        for path in PROTOCOL_DIR.glob(pattern):
            path.unlink()

    pycache = PROTOCOL_DIR / "__pycache__"
    if pycache.exists():
        shutil.rmtree(pycache)

def build_libqlcp(cmake_dir: Path) -> None:
    run(
        [
            "cmake",
            "-S",
            str(QLCP_DIR),
            "-B",
            str(cmake_dir),
            "-DBUILD_SHARED_LIBS=ON",
            "-DCMAKE_BUILD_TYPE=Release",
        ],
    )
    run(["cmake", "--build", str(cmake_dir), "--target", "qlcp"])

    candidates = sorted(cmake_dir.rglob("libqlcp.so"))
    if not candidates:
        message = f"Could not find built qlcp library under {cmake_dir}"
        raise RuntimeError(message)
    shutil.copy2(max(candidates, key=lambda path: path.stat().st_mtime_ns), LIBQLCP)

def expand_qlcp_header() -> None:
    result = run(["gcc", "-E", str(QLCP_INCLUDE / "qlcp_lib.h")], capture=True)
    expanded: list[str] = []
    include_line = False

    # Keep project declarations after preprocessing while dropping system headers
    # that CFFI does not need to parse.
    for line in result.stdout.splitlines():
        if line.startswith("# "):
            parts = line.split(maxsplit=3)
            marker = parts[2].strip('"') if len(parts) >= 3 else ""
            is_builtin = marker.startswith("<") and marker.endswith(">")
            is_system = marker.startswith(("/usr/", "/lib/", "/lib64/", "/include/", "/opt/"))
            include_line = not is_builtin and not is_system
            continue
        if include_line:
            expanded.append(line)

    if not any(line.strip() for line in expanded):
        raise RuntimeError("Expanded qlcp header is empty")
    EXPANDED_HEADER.write_text("\n".join(expanded) + "\n")

def extension_suffix() -> str:
    suffix = sysconfig.get_config_var("EXT_SUFFIX")
    if not suffix:
        raise RuntimeError("Python did not report an extension suffix for this platform")
    return suffix

def build_cffi_extension(cffi_dir: Path) -> None:
    ffi = cffi.FFI()
    header_cdef = EXPANDED_HEADER.read_text()
    generated_constant_cdef = "#define QLCP_HEADER_SIZE ..."
    cdef_source = f"{header_cdef}\n{generated_constant_cdef}"
    ffi.cdef(cdef_source)
    ffi.set_source(
        "_qlcp",
        '#include "qlcp_lib.h"',
        include_dirs=[str(QLCP_INCLUDE)],
        libraries=["qlcp"],
        library_dirs=[str(LIB_DIR)],
        extra_link_args=["-Wl,-rpath,$ORIGIN/../_lib"],
    )

    cffi_dir.mkdir(parents=True, exist_ok=True)
    built_extension = Path(ffi.compile(tmpdir=str(cffi_dir), verbose=True))
    shutil.copy2(built_extension, PROTOCOL_DIR / f"_qlcp{extension_suffix()}")
    (PROTOCOL_DIR / "__init__.py").write_text(f"{GENERATED_BANNER}\n")

    sys.path.insert(0, str(ROOT))
    sys.modules.pop("libqretprop._protocol._qlcp", None)
    importlib.invalidate_caches()
    lib = importlib.import_module("libqretprop._protocol._qlcp").lib
    write_stub(lib)

    pycache = PROTOCOL_DIR / "__pycache__"
    if pycache.exists():
        shutil.rmtree(pycache)

def write_stub(lib: Any) -> None:
    enums = {name: getattr(lib, name) for name in dir(lib) if isinstance(getattr(lib, name), int)}
    functions = [name for name in dir(lib) if callable(getattr(lib, name))]

    lines = [
        GENERATED_BANNER,
        "from typing import Any",
        "",
        "from cffi.api import FFI",
        "",
        "ffi: FFI",
        "",
        "class _Lib:",
        *(f"    {name}: int  # {value:#04x}" for name, value in sorted(enums.items())),
        *(f"    def {name}(self, *args: Any) -> Any: ..." for name in sorted(functions)),
        "",
        "lib: _Lib",
        "",
    ]

    (PROTOCOL_DIR / "_qlcp.pyi").write_text("\n".join(lines))

def build_protocol() -> None:
    clean_protocol_artifacts()
    with tempfile.TemporaryDirectory(prefix="prop-teststand-qlcp-build-") as tmp:
        build_dir = Path(tmp)
        build_libqlcp(build_dir / "cmake")
        expand_qlcp_header()
        build_cffi_extension(build_dir / "cffi")

class QLCPBuildHook(BuildHookInterface):
    def initialize(self, _version: str, build_data: dict[str, object]) -> None:
        if self.target_name not in BUILD_TARGETS:
            return

        if os.environ.get(SKIP_ENV) == "1":
            print(f"Skipping QLCP protocol build ({SKIP_ENV}=1)")
            return

        build_protocol()
        build_data["pure_python"] = False
        build_data["infer_tag"] = True

def get_build_hook() -> type[QLCPBuildHook]:
    return QLCPBuildHook
