name: Docker Build (Release)

on:
    release:
        types: [published]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write # Required for pushing to GHCR

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Extract Docker metadata (logs)
              id: meta-logs
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository }}-logs
                  tags: |
                      type=raw,value=latest
                      type=raw,value=${TAG_REF#refs/tags/}

            - name: Extract Docker metadata (server)
              id: meta-server
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository }}-server
                  tags: |
                      type=raw,value=latest
                      type=raw,value=${TAG_REF#refs/tags/}

            - name: Build and push Docker image (server)
              uses: docker/build-push-action@v5
              with:
                  file: ./Dockerfile.server
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ steps.meta-server.outputs.tags }}
                  labels: ${{ steps.meta-server.outputs.labels }}

            - name: Build and push Docker image (logs)
              uses: docker/build-push-action@v5
              with:
                  file: ./Dockerfile.logs
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ steps.meta-logs.outputs.tags }}
                  labels: ${{ steps.meta-logs.outputs.labels }}
